[project]
name = "california-simple"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "jinja2",
  "numpy",
  "pandas",
  "scikit-learn",
  "joblib",
  "seaborn",
  "plotly",
  "pydantic>=2",
]

[tool.uv]
