name: CICD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: California_Housing_End_to_End
          push: true
          tags: ghcr.io/${{ github.repository }}/california-simple:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ secrets.DEPLOY_HOST != '' }}
    steps:
      - name: SSH deploy (pull & restart)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}/california-simple:latest || true
            docker rm -f ${{ secrets.APP_NAME }} || true
            docker run -d --name ${{ secrets.APP_NAME }} \
              -p ${{ secrets.PORT }}:8000 \
              ghcr.io/${{ github.repository }}/california-simple:latest
